[package]
edition = "2021"
name = "near-components-core"
version = "0.1.0"
publish = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-components = {path = "../.."}
microjson = "0.1.0"

[features]
wee_alloc = ["near-components/wee_alloc"]
